# Generated by Django 4.0.3 on 2022-05-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_product_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
